import os

fr_dict = {
    "Alerts": "Alertes",
    "Alert Center": "Centre d'alertes",
    "Track and manage all system alerts across your ponds.": "Suivez et gérez toutes les alertes système.",
    "Mark all as read": "Tout marquer comme lu",
    "Filter alerts by status": "Filtrer les alertes",
    "All": "Tout",
    "Open": "Ouvert",
    "Acknowledged": "Reconnu",
    "Resolved": "Résolu",
    "Title": "Titre",
    "Pond": "Bassin",
    "Farm": "Ferme",
    "Type": "Type",
    "Severity": "Sévérité",
    "Status": "Statut",
    "Date": "Date",
    "Critical": "Critique",
    "High": "Élevé",
    "Warning": "Avertissement",
    "Info": "Info",
    "Mark as read": "Marquer lu",
    "Ack": "Rec",
    "Done": "Fait",
    "%(time)s ago": "il y a %(time)s",
    "Updated %(time)s ago": "Mis à jour il y a %(time)s",
    "Last sensor sync: %(time)s ago": "Dernière synchro : il y a %(time)s",
    "View Pond": "Voir le bassin",
    "All Clear!": "Tout va bien !",
    "No alerts found — all ponds are operating normally.": "Aucune alerte — tout fonctionne normalement.",
    "View Ponds": "Voir les bassins",
    "Main": "Principal",
    "Dashboard": "Tableau de Bord",
    "Farms": "Fermes",
    "Ponds": "Bassins",
    "Account": "Compte",
    "Profile": "Profil",
    "Logout": "Déconnexion",
    "Open menu": "Ouvrir le menu",
    "Switch language": "Changer de langue",
    "Select language": "Choisir la langue",
    "Notifications": "Notifications",
    "No new notifications": "Pas de nouvelles notifications",
    "View all alerts": "Voir toutes les alertes",
    "Welcome back, %(username)s": "Bon retour, %(username)s",
    "Smart Aquaculture Command Center": "Centre de Commandement Intelligent",
    "Monitor your farms, track real-time water quality, and respond to alerts — all in one place.": "Gérez vos fermes et la qualité de l'eau en temps réel.",
    "Ponds Overview": "Aperçu des Bassins",
    "System Overview": "Aperçu du système",
    "Total Fish Stock": "Stock total de poissons",
    "Active Alerts": "Alertes Actives",
    "Good": "Bon",
    "Water Quality Index": "Indice Qualité de l'Eau",
    "Equipment Status": "État des équipements",
    "Quick Access": "Accès Rapide",
    "My Farms": "Mes Fermes",
    "Manage all sites": "Gérer les sites",
    "View water quality": "Voir la qualité de l'eau",
    "Resolve issues": "Résoudre les problèmes",
    "Settings & account": "Paramètres",
    "Sign In": "Se connecter",
    "Smart Aquaculture Monitoring": "Surveillance Intelligente de l'Aquaculture",
    "Invalid username or password. Please try again.": "Identifiant ou mot de passe invalide.",
    "Username": "Nom d'utilisateur",
    "Enter your username": "Entrez votre nom",
    "Password": "Mot de passe",
    "Enter your password": "Entrez votre mot de passe",
    "Live Monitor": "Moniteur en Direct",
    "Normal": "Normal",
    "AI Active": "IA Active",
    "OFFLINE": "HORS LIGNE",
    "No Live Stream": "Pas de flux",
    "IoT Readings": "Capteurs IoT",
    "Live": "Direct",
    "Temp & DO": "Temp & OD",
    "Quick Actions": "Actions Rapides",
    "Generate 24hr Report": "Générer Rapport 24h",
    "Calibrate Sensors": "Calibrer",
    "Fish Species": "Espèce",
    "Fish Count": "Quantité",
    "Last Updated": "Mis à jour",
    "AI Detections": "Détections IA",
    "Medium": "Moyen",
    "Low": "Faible",
    "%(conf)s conf": "%(conf)s conf",
    "Recent Alerts": "Alertes Récentes",
    "View All": "Voir Tout",
    "OPEN": "OUVERT",
    "Temperature (°C)": "Température (°C)",
    "Dissolved Oxygen (mg/L)": "Oxygène dissous (mg/L)",
    "Temp": "Temp",
    "%(fcount)s fish": "%(fcount)s poissons",
    "View Live Monitor": "Voir le direct",
    "No Ponds Found": "Aucun bassin",
    "Go to Farms": "Aller aux fermes"
}

ar_dict = {
    "Alerts": "التنبيهات",
    "Alert Center": "مركز التنبيهات",
    "Track and manage all system alerts across your ponds.": "تتبع وإدارة جميع تنبيهات النظام في أحواضك.",
    "Mark all as read": "تحديد الكل كمقروء",
    "Filter alerts by status": "تصفية التنبيهات",
    "All": "الكل",
    "Open": "مفتوح",
    "Acknowledged": "تم الاستلام",
    "Resolved": "تم الحل",
    "Title": "العنوان",
    "Pond": "الحوض",
    "Farm": "المزرعة",
    "Type": "النوع",
    "Severity": "الأهمية",
    "Status": "الحالة",
    "Date": "التاريخ",
    "Critical": "حرج",
    "High": "عالي",
    "Warning": "تحذير",
    "Info": "معلومة",
    "Mark as read": "تحديد كمقروء",
    "Ack": "تأكيد",
    "Done": "تم",
    "%(time)s ago": "منذ %(time)s",
    "Updated %(time)s ago": "تم التحديث منذ %(time)s",
    "Last sensor sync: %(time)s ago": "آخر مزامنة: منذ %(time)s",
    "View Pond": "عرض الحوض",
    "All Clear!": "كل شيء على ما يرام!",
    "No alerts found — all ponds are operating normally.": "لا توجد تنبيهات — جميع الأحواض تعمل بشكل طبيعي.",
    "View Ponds": "عرض الأحواض",
    "Main": "الرئيسية",
    "Dashboard": "لوحة القيادة",
    "Farms": "المزارع",
    "Ponds": "الأحواض",
    "Account": "الحساب",
    "Profile": "الملف الشخصي",
    "Logout": "تسجيل الخروج",
    "Open menu": "فتح القائمة",
    "Switch language": "تغيير اللغة",
    "Select language": "اختر اللغة",
    "Notifications": "الإشعارات",
    "No new notifications": "لا توجد إشعارات جديدة",
    "View all alerts": "عرض جميع التنبيهات",
    "Welcome back, %(username)s": "مرحباً بعودتك، %(username)s",
    "Smart Aquaculture Command Center": "مركز القيادة الذكي لتربية الأحياء المائية",
    "Monitor your farms, track real-time water quality, and respond to alerts — all in one place.": "راقب مزارعك وجودة المياه في الوقت الفعلي وأجب على التنبيهات.",
    "Ponds Overview": "نظرة عامة على الأحواض",
    "System Overview": "نظرة عامة على النظام",
    "Total Fish Stock": "إجمالي مخزون الأسماك",
    "Active Alerts": "التنبيهات النشطة",
    "Good": "جيد",
    "Water Quality Index": "مؤشر جودة المياه",
    "Equipment Status": "حالة المعدات",
    "Quick Access": "وصول سريع",
    "My Farms": "مزارعي",
    "Manage all sites": "إدارة جميع المواقع",
    "View water quality": "رؤية جودة المياه",
    "Resolve issues": "حل المشاكل",
    "Settings & account": "الإعدادات والحساب",
    "Sign In": "تسجيل الدخول",
    "Smart Aquaculture Monitoring": "المراقبة الذكية لتربية الأحياء المائية",
    "Invalid username or password. Please try again.": "اسم المستخدم أو كلمة المرور غير صالحة.",
    "Username": "اسم المستخدم",
    "Enter your username": "أدخل اسم المستخدم",
    "Password": "كلمة المرور",
    "Enter your password": "أدخل كلمة المرور",
    "Live Monitor": "مراقب مباشر",
    "Normal": "طبيعي",
    "AI Active": "الذكاء الاصطناعي نشط",
    "OFFLINE": "غير متصل",
    "No Live Stream": "لا يوجد بث مباشر",
    "IoT Readings": "قراءات IoT",
    "Live": "مباشر",
    "Temp & DO": "الحرارة والأكسجين",
    "Quick Actions": "إجراءات سريعة",
    "Generate 24hr Report": "إنشاء تقرير 24 ساعة",
    "Calibrate Sensors": "معايرة المستشعرات",
    "Fish Species": "أنواع الأسماك",
    "Fish Count": "عدد الأسماك",
    "Last Updated": "آخر تحديث",
    "AI Detections": "اكتشافات الذكاء الاصطناعي",
    "Medium": "متوسط",
    "Low": "منخفض",
    "%(conf)s conf": "%(conf)s ثقة",
    "Recent Alerts": "التنبيهات الأخيرة",
    "View All": "عرض الكل",
    "OPEN": "مفتوح",
    "Temperature (°C)": "الحرارة (°C)",
    "Dissolved Oxygen (mg/L)": "الأكسجين المذاب (mg/L)",
    "Temp": "الحرارة",
    "%(fcount)s fish": "%(fcount)s سمكة",
    "View Live Monitor": "عرض مباشر",
    "No Ponds Found": "لا توجد أحواض",
    "Go to Farms": "الذهاب إلى المزارع"
}

def translate_po(file_path, dictionary):
    if not os.path.exists(file_path):
        print(f"Skipping {file_path}")
        return
        
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    out_lines = []
    current_msgid = None
    
    for line in lines:
        if line.startswith('msgid "'):
            current_msgid = line.replace('msgid "', '').rstrip('"\n')
            out_lines.append(line)
        elif line.startswith('msgstr "') and current_msgid:
            # check multiline handling (rudimentary here)
            translated = dictionary.get(current_msgid, "")
            out_lines.append(f'msgstr "{translated}"\n')
            current_msgid = None
        else:
            out_lines.append(line)
            
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(out_lines)

if __name__ == "__main__":
    translate_po("locale/fr/LC_MESSAGES/django.po", fr_dict)
    translate_po("locale/ar/LC_MESSAGES/django.po", ar_dict)
    print("PO files translated successfully.")
