# Generated by Django 4.2.29 on 2026-03-21 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fish_species', models.CharField(blank=True, default='', max_length=200)),
                ('fish_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='monitoring.farm')),
            ],
            options={
                'verbose_name': 'Pond',
                'ordering': ['farm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('oxygen', 'Dissolved Oxygen'), ('pH', 'pH Level'), ('salinity', 'Salinity'), ('turbidity', 'Turbidity')], max_length=50)),
                ('device_code', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('faulty', 'Faulty')], default='online', max_length=20)),
                ('installed_at', models.DateField()),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='monitoring.pond')),
            ],
            options={
                'verbose_name': 'Sensor',
                'ordering': ['pond', 'sensor_type'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Farm Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stream_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20)),
                ('installed_at', models.DateField()),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='monitoring.pond')),
            ],
            options={
                'verbose_name': 'Camera',
                'ordering': ['pond', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('alert_type', models.CharField(choices=[('water_quality', 'Water Quality'), ('disease', 'Disease'), ('oxygen', 'Low Oxygen'), ('temperature', 'Temperature'), ('pollution', 'Pollution'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.pond')),
            ],
            options={
                'verbose_name': 'Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, default='')),
                ('prediction_text', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='monitoring.camera')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_detections', to='monitoring.pond')),
            ],
            options={
                'verbose_name': 'AI Detection',
                'ordering': ['-detected_at'],
            },
        ),
    ]
