# Generated by Django 4.2.29 on 2026-03-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_time', models.DateTimeField()),
                ('hour_offset', models.PositiveSmallIntegerField()),
                ('temp', models.FloatField()),
                ('do', models.FloatField()),
                ('ph', models.FloatField()),
                ('ammonia', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Warning', 'Warning'), ('Risk', 'Risk')], max_length=10)),
                ('issues', models.TextField(blank=True, default='')),
                ('actions', models.TextField(blank=True, default='')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='monitoring.pond')),
            ],
            options={
                'ordering': ['target_time'],
                'unique_together': {('pond', 'target_time')},
            },
        ),
    ]
