# Generated by Django 4.2.29 on 2026-03-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ESPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mac_address', models.CharField(help_text='e.g. 00:1B:44:11:3A:B7', max_length=50, unique=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='monitoring.farm')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='monitoring.espdevice')),
            ],
        ),
    ]
