# Generated by Django 4.2.29 on 2026-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_sensorreading_recorded_at_espdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude (e.g., 33.5731)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude (e.g., -7.5898)', null=True),
        ),
    ]
