# Generated by Django 5.0 on 2026-04-03 13:48

import uuid
from django.db import migrations, models


def fix_invalid_uuids(apps, schema_editor):
    DeviceCommand = apps.get_model('monitoring', 'DeviceCommand')
    for cmd in DeviceCommand.objects.all():
        try:
            uuid.UUID(str(cmd.message_id))
        except (ValueError, TypeError):
            cmd.message_id = str(uuid.uuid4())
            cmd.save()

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_farm_latitude_farm_longitude'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_uuids),
        migrations.AlterField(
            model_name='devicecommand',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
